language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t kirolosayad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kirolosayad/docker-react npm run test